# Changes here will be overwritten by Copier
_commit: v7.3.0-24-g169e035
_src_path: gh:eccenca/cmem-plugin-template
author_mail: rangareddy.nukala@eccenca.com
author_name: Sai Ranga Reddy Nukala
github_page: ''
project_description: Send or receive data from your organization´s Salesforce account.
project_slug: salesforce
project_type: plugin
pypi: true

