# Changes here will be overwritten by Copier
_commit: v7.3.0-24-g169e035
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-salesforce
project_description: Send or receive data from your organization´s Salesforce account.
project_slug: salesforce
project_type: plugin
pypi: true

