---
name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" and "develop" branch
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: debian-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv if cache exists
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: build
        run: |
          task build

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source tarball
          path: dist/*.tar.gz

